///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyChatHeadGroupId = "group_id";
const String _jsonKeyChatHeadMsgId = "msg_id";
const String _jsonKeyChatHeadSender = "sender";
const String _jsonKeyChatHeadMsg = "msg";
const String _jsonKeyChatHeadSenderId = "sender_id";
const String _jsonKeyChatHeadSenderProfileUrl = "sender_profile_url";
const String _jsonKeyChatHeadIsSeen = "is_seen";
const String _jsonKeyChatHeadIsDelivered = "is_delivered";
const String _jsonKeyChatHeadTimestamp = "timestamp";
class ChatHead {
/*
{
  "group_id": "",
  "msg_id": "",
  "sender": "",
  "msg": "",
  "sender_id": "",
  "sender_profile_url": "",
  "is_seen": true,
  "is_delivered": true,
  "timestamp": 2222222
}
*/

  String? groupId;
  String? msgId;
  String? sender;
  String? msg;
  String? senderId;
  String? senderProfileUrl;
  bool? isSeen;
  bool? isDelivered;
  String? timestamp;
  Map<String, dynamic> __origJson = {};

  ChatHead({
    this.groupId,
    this.msgId,
    this.sender,
    this.msg,
    this.senderId,
    this.senderProfileUrl,
    this.isSeen,
    this.isDelivered,
    this.timestamp,
  });
  ChatHead.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    groupId = json[_jsonKeyChatHeadGroupId]?.toString();
    msgId = json[_jsonKeyChatHeadMsgId]?.toString();
    sender = json[_jsonKeyChatHeadSender]?.toString();
    msg = json[_jsonKeyChatHeadMsg]?.toString();
    senderId = json[_jsonKeyChatHeadSenderId]?.toString();
    senderProfileUrl = json[_jsonKeyChatHeadSenderProfileUrl]?.toString();
    isSeen = json[_jsonKeyChatHeadIsSeen];
    isDelivered = json[_jsonKeyChatHeadIsDelivered];
    timestamp = json[_jsonKeyChatHeadTimestamp]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[_jsonKeyChatHeadGroupId] = groupId;
    data[_jsonKeyChatHeadMsgId] = msgId;
    data[_jsonKeyChatHeadSender] = sender;
    data[_jsonKeyChatHeadMsg] = msg;
    data[_jsonKeyChatHeadSenderId] = senderId;
    data[_jsonKeyChatHeadSenderProfileUrl] = senderProfileUrl;
    data[_jsonKeyChatHeadIsSeen] = isSeen;
    data[_jsonKeyChatHeadIsDelivered] = isDelivered;
    data[_jsonKeyChatHeadTimestamp] = timestamp;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
